package com.chicago.dtc.controller.wsdl;

import com.chicago.dtc.model.schema.GetPokemonRequest;
import com.chicago.dtc.model.schema.GetPokemonResponse;
import com.chicago.dtc.model.schema.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2023-05-24T15:48:59.516-05:00
 * Generated source version: 3.3.0
 *esta es la interfaz de usuario en la arquitectura mvc
 */
@WebService(targetNamespace = "pokemonWS/wsdl", name = "pokemonWSPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PokemonWSPort {

    @WebMethod(operationName = "GetPokemon", action = "pokemonWS/GetPokemon")
    @WebResult(name = "GetPokemonResponse", targetNamespace = "pokemonWS/schema", partName = "parameters")
    public GetPokemonResponse getPokemon(
        @WebParam(partName = "parameters", name = "GetPokemonRequest", targetNamespace = "pokemonWS/schema")
        GetPokemonRequest parameters
    );
}
