package com.chicago.dtc.controller.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2023-05-24T15:48:59.583-05:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "pokemonWS",
                  wsdlLocation = "file:/C:/Users/nickog/Desktop/soap-ws-demos/servidorws/src/main/resources/wsdl/pokemonWS.wsdl",
                  targetNamespace = "pokemonWS/wsdl")
public class PokemonWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("pokemonWS/wsdl", "pokemonWS");
    public final static QName PokemonWSSOAPBinding = new QName("pokemonWS/wsdl", "pokemonWSSOAPBinding");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/nickog/Desktop/soap-ws-demos/servidorws/src/main/resources/wsdl/pokemonWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PokemonWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/nickog/Desktop/soap-ws-demos/servidorws/src/main/resources/wsdl/pokemonWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PokemonWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PokemonWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PokemonWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PokemonWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PokemonWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PokemonWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PokemonWSPort
     */
    @WebEndpoint(name = "pokemonWSSOAPBinding")
    public PokemonWSPort getPokemonWSSOAPBinding() {
        return super.getPort(PokemonWSSOAPBinding, PokemonWSPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PokemonWSPort
     */
    @WebEndpoint(name = "pokemonWSSOAPBinding")
    public PokemonWSPort getPokemonWSSOAPBinding(WebServiceFeature... features) {
        return super.getPort(PokemonWSSOAPBinding, PokemonWSPort.class, features);
    }

}
