package pokemonws.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2023-05-24T17:41:37.030-05:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "pokemonWS/wsdl", name = "pokemonWSPort")
@XmlSeeAlso({pokemonws.schema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PokemonWSPort {

    @WebMethod(operationName = "GetPokemon", action = "pokemonWS/GetPokemon")
    @WebResult(name = "GetPokemonResponse", targetNamespace = "pokemonWS/schema", partName = "parameters")
    public pokemonws.schema.GetPokemonResponse getPokemon(
        @WebParam(partName = "parameters", name = "GetPokemonRequest", targetNamespace = "pokemonWS/schema")
        pokemonws.schema.GetPokemonRequest parameters
    );
}
